---
title: A Brief Look at Spotify
author: Bryan Armpriest
date: 2025-03-02
categories: [python, pandas, music]
image: "spotify.png"
toc: true
---

In [ ]:
#Let's load up some data from Spotify so that we can take a look at it!

import pandas as pd

spotify = pd.read_csv('https://bcdanl.github.io/data/spotify_all.csv')

In [ ]:
spotify.info()
spotify

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198005 entries, 0 to 198004
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   pid            198005 non-null  int64
 1   playlist_name  198005 non-null  object
 2   pos            198005 non-null  int64
 3   artist_name    198005 non-null  object
 4   track_name     198005 non-null  object
 5   duration_ms    198005 non-null  int64
 6   album_name     198005 non-null  object
dtypes: int64(3), object(4)
memory usage: 10.6+ MB

,pid,playlist_name,pos,artist_name,track_name,duration_ms,album_name
0,0,Throwbacks,0,Missy Elliott,Lose Control (feat. Ciara & Fat Man Scoop),226863,The Cookbook
1,0,Throwbacks,1,Britney Spears,Toxic,198800,In The Zone
2,0,Throwbacks,2,Beyoncé,Crazy In Love,235933,Dangerously In Love (Alben für die Ewigkeit)
3,0,Throwbacks,3,Justin Timberlake,Rock Your Body,267266,Justified
4,0,Throwbacks,4,Shaggy,It Wasn't Me,227600,Hot Shot
...,...,...,...,...,...,...,...
198000,999998,✝️,6,Chris Tomlin,Waterfall,209573,Love Ran Red
198001,999998,✝️,7,Chris Tomlin,The Roar,220106,Love Ran Red
198002,999998,✝️,8,Crowder,Lift Your Head Weary Sinner (Chains),224666,Neon Steeple
198003,999998,✝️,9,Chris Tomlin,We Fall Down,280960,How Great Is Our God: The Essential Collection
198004,999998,✝️,10,Caleb and Kelsey,"10,000 Reasons / What a Beautiful Name",178189,"10,000 Reasons / What a Beautiful Name"

Warning: total number of rows (198005) exceeds max_rows (20000). Limiting to first (20000) rows.

To start, I want to see if my favorite band is included in this DataFrame. I will do this two different ways, first by indexing (and searching) and then by using filtering methods. Both of the following code chunks provide the same filtered dataframe.

In [ ]:
#Indexing, first we must set the index of the DataFrame to a new variable
spotify_name = spotify.set_index(['artist_name'])

#Now we just have to search for Coldplay!
spotify_name.loc[['Coldplay']]

,pid,playlist_name,pos,track_name,duration_ms,album_name
artist_name,,,,,,
Coldplay,31,Running 2.0,88,Hymn For The Weekend - Seeb Remix,212647,A Head Full Of Dreams Tour Edition
Coldplay,45,angst,43,The Scientist,309600,A Rush Of Blood To The Head
Coldplay,51,Kevin,27,Midnight,294666,Ghost Stories
Coldplay,85,Gym,1,Adventure Of A Lifetime,263786,A Head Full Of Dreams
Coldplay,85,Gym,2,Hymn For The Weekend,258826,A Head Full Of Dreams
...,...,...,...,...,...,...
Coldplay,999968,chill songs,89,A Sky Full of Stars,268466,Ghost Stories
Coldplay,999968,chill songs,90,See You Soon,171373,The Blue Room
Coldplay,999979,summer 2017,18,Paradise,278719,Mylo Xyloto
Coldplay,999984,Lake,9,Adventure Of A Lifetime,263786,A Head Full Of Dreams
Coldplay,999989,PARTAY,23,Hymn For The Weekend - Seeb Remix,212647,A Head Full Of Dreams Tour Edition

In [26]:
#Filtering -> use of a the query() method
coldplay = spotify.query("artist_name == 'Coldplay'")
coldplay

,pid,playlist_name,pos,artist_name,track_name,duration_ms,album_name
1732,31,Running 2.0,88,Coldplay,Hymn For The Weekend - Seeb Remix,212647,A Head Full Of Dreams Tour Edition
2755,45,angst,43,Coldplay,The Scientist,309600,A Rush Of Blood To The Head
2973,51,Kevin,27,Coldplay,Midnight,294666,Ghost Stories
4859,85,Gym,1,Coldplay,Adventure Of A Lifetime,263786,A Head Full Of Dreams
4860,85,Gym,2,Coldplay,Hymn For The Weekend,258826,A Head Full Of Dreams
...,...,...,...,...,...,...,...
196152,999968,chill songs,89,Coldplay,A Sky Full of Stars,268466,Ghost Stories
196153,999968,chill songs,90,Coldplay,See You Soon,171373,The Blue Room
196787,999979,summer 2017,18,Coldplay,Paradise,278719,Mylo Xyloto
196980,999984,Lake,9,Coldplay,Adventure Of A Lifetime,263786,A Head Full Of Dreams
197493,999989,PARTAY,23,Coldplay,Hymn For The Weekend - Seeb Remix,212647,A Head Full Of Dreams Tour Edition

Now, I'm curious to see how many times Coldplay appears in this particular dataset that contains 1 million different playlists.

I am also particularly interested in the number of unique track_names that appear within this DataFrame.

In [31]:
coldplay.shape[0] #there are 483 observations of Coldplay in this data!

483

In [41]:
spotify.shape[0]

198005

In [42]:
483/198005 #Coldplay shows up in less than 1% of playlists, I suppose there is a very specific mood of a playlist that calls for Coldplay.

0.002439332340092422

In [33]:
coldplay['track_name'].nunique() #74 unique tracks

74

I also thought it would be interesting to see the mean position in which coldplay songs are added to these playlists (especially in comparison to the average position for all observations in the dataframe).

In [35]:
coldplay['pos'].mean() #Around the 45th position!

44.79710144927536

In [36]:
spotify['pos'].mean()

54.39170728011919

Finally, let's look at the length of these songs.

In [37]:
spotify['duration_ms'].mean()

234740.84469079063

In [38]:
coldplay['duration_ms'].mean() #coldplay songs seem to be longer! lets see if there are any in particular through sorting.

268694.7039337474

In [40]:
coldplay.sort_values(['duration_ms'], ascending = False)
#With this information in the dataframe, they range from 465957ms to 136866ms

,pid,playlist_name,pos,artist_name,track_name,duration_ms,album_name
122515,1827,Now,0,Coldplay,O,465957,Ghost Stories
59456,881,EDC,31,Coldplay,Every Teardrop Is a Waterfall - Coldplay vs. S...,408828,Until Now
41930,631,house,11,Coldplay,Every Teardrop Is a Waterfall - Coldplay vs. S...,408828,Until Now
4861,85,Gym,3,Coldplay,Up&Up,405320,A Head Full Of Dreams
107839,1607,sleeps,29,Coldplay,Gravity,380946,Talk
...,...,...,...,...,...,...,...
196153,999968,chill songs,90,Coldplay,See You Soon,171373,The Blue Room
135923,999023,Pop songs,41,Coldplay,Life In Technicolor,149133,Viva La Vida Or Death And All His Friends
59961,887,Reception,61,Coldplay,Life In Technicolor,149133,Viva La Vida Or Death And All His Friends
9437,144,picks,25,Coldplay,U.F.O.,137819,Mylo Xyloto
44608,665,recommendations !!,48,Coldplay,Don't Panic,136866,Parachutes

Looking back at my very brief look at Coldplay observations within the Spotify DataFrame, I learned quite a bit from the data.

1.   Coldplay showed up in a fairly low number of playlists (less than 1%)
2.   There was quite a range in the length of the tracks, from 136 seconds to 465 seconds.
3.   When comparing the average position, Coldplay comes slightly sooner in playlists than the average for all songs.

### As always, thanks for reading!